@startuml

Class Game{
    id: String
    score: int
}

Class Round{
    roundNumber: int
    wordToGuess: String
    hint: String
}

Class Word{
    value: String
    length: Int
}

Class Feedback {
    attempt: String
}

Enum Mark{
    CORRECT
    ABSENT
    PRESENT
    INVALID
}

Enum RoundStatus{
    WAITING
    PLAYING
    DEFEATED
}

Class User{
    id: String
    email: String
    name: String
    password: String
}

Game -down- User : player
Game -left- RoundStatus : roundStatus
Game -right- Round : rounds
Round -down- Feedback : guesses
Feedback -right- Mark : marks


@enduml