name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13 for x64
          uses: actions/setup-java@v1
          with:
            java-version: '13'
            architecture: x64
      - name: Build with Maven
        run: mvnw -B verify -Dspring.profiles.active=ci